# Python package
# Create and test a Python package on multiple Python versions.
trigger:
- main

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python39:
      python.version: '3.9'
    Python310:
      python.version: '3.10'
    Python311:
      python.version: '3.11'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    # 1. Aggiorna pip e installa TUTTE le dipendenze necessarie
    python -m pip install --upgrade pip
    pip install requests pytest pytest-azurepipelines
    
    # 2. Configura l'ambiente ed esegui i test nello stesso blocco
    export PYTHONPATH=.
    pytest
  displayName: 'Installa dipendenze ed esegui pytest'
